In [3]:
import numpy as np
arr = np.arange(1,17)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [4]:
arr.reshape(-1,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

In [5]:
arr.reshape(-1,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]]])

In [7]:
new_arr = arr.copy()
new_arr[10] = 99
arr, new_arr

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 99, 12, 13, 14, 15, 16]))

In [9]:
lst = [1,4]
lst1 = [1,5]
lst + lst1

[1, 4, 1, 5]

In [11]:
import numpy as np

x =np.arange(5)
x.shape


(5,)

In [14]:
y = x.reshape(1,-1)
y.shape

(1, 5)

In [15]:
y.reshape(-1,1)
y.shape

(1, 5)

In [19]:
x = np.array([[1,2],[2,4]])

In [20]:
np.linalg.inv(x)

LinAlgError: Singular matrix

In [22]:
x * x

array([[ 1,  4],
       [ 4, 16]])

In [23]:
np.matmul(x,x)

array([[ 5, 10],
       [10, 20]])

In [24]:
x @ x

array([[ 5, 10],
       [10, 20]])

In [2]:
list_of_lists = [[1, 2, 'a'], [], ['MyClass1', 'MyClass2']]
len(list_of_lists)

3

In [3]:
def say_hello():
    print('Hello')