In [35]:
import numpy as np
import pandas as pd
from scipy import stats

In [2]:
sample_ages = [32, 34, 29, 29, 22, 39, 38, 37, 38, 36, 30, 26, 22, 22]

Ho: mu = 30

ha: mu > 30

In [14]:
mu = 30
mean = np.mean(sample_ages)
var = np.var(sample_ages)
n = len(sample_ages)
se = np.sqrt(var/n)

In [12]:
alpha = 0.05

In [13]:
norm = stats.norm(mu, se)

In [15]:
1 - norm.cdf(mean)

0.26765179862315036

Fail to reject Null

In [19]:
z = (mean - mu) / se
z

0.6199304198780666

In [25]:
1 - stats.norm().cdf(z)

0.26765179862315036

In [23]:

norm.ppf(z)

30.492471479307444

# Assessment 0 Practice

In [27]:
def fizz_buzz():
    '''Returns the numbers from 1 to 100 into list. But for
    multiples of three append "Fizz" instead of the number and for the multiples
    of five append "Buzz". For numbers which are multiples of both three and five
    append "FizzBuzz".

    The first five elements of the output list are:
        lst = [1, 2, "Fizz", 4, "Buzz", ....]

    Parameters
    ----------
    None

    Returns
    -------
    list
    '''
    return ['FizzBuzz' if n % 3 == 0 and n % 5 == 0 else 'Fizz' if n % 3 == 0 else 'Buzz' if n % 5 == 0 else \
            n for n in range(1,100+1)]
    
# fizz_buzz()         

In [29]:
def count_characters(string):
    '''
    Return a dictionary which contains
    a count of the number of times each character appears in the string.
    Characters which with a count of 0 should not be included in the
    output dictionary.

    FOR FULL POINTS DON'T USE IMPORTS.

    Parameters
    ----------
    string: str

    Returns
    -------
    dict
        A dictionary with counts of each character in string
    '''
    
    count_d = {}
    
    for char in string:
        if char not in count_d:
            count_d[char] = 0
        count_d[char] += 1
    
    return count_d


# count_characters('return a dictionary which contains')     
    

In [33]:
def merge_dictionaries(d1, d2):
    '''Returns a new dictionary containing all the keys from d1 and d2 with
    their associated values. If a key is in both dictionaries, the new value is
    the sum of the two values from d1 and d2.

    FOR FULL POINTS DON'T USE IMPORTS AND MAXIMUM ONE LOOP.

    Parameters
    ----------
    d1, d2: dictionary, dictionary

    Returns
    -------
    dictionary
    '''
    merge_d = d1.copy()
    
    for k, v in d2.items():
        print(k,v)
        if k not in merge_d:
            merge_d[k] = v
        else:
            merge_d[k] += v
    return merge_d

d1 = {'a':3,'b':4,'c':0}
d2 = {'a':7,'d':4}

# merge_dictionaries(d1, d2)

In [34]:
def cookie_jar(a, b):
    '''
    There are two jars of cookies.
    Each has chocolate and peanut butter cookies.
    Input 'a' is the fraction of cookies in Jar A which are chocolate.
    Input 'b' is the fraction of cookies in Jar B which are chocolate.
    A jar is chosen at random and a cookie is drawn.
    The cookie is chocolate.
    Return the probability that the cookie came from Jar A.

    Parameters
    ----------
    a: float
        Probability of drawing a chocolate cooking from Jar A
    b: float
        Probability of drawing a chocolate cooking from Jar B

    Returns
    -------
    float
        Conditional probability that cookie was drawn from Jar A given
        that a chocolate cookie was drawn.    
    '''
    return a*0.5 / (a*0.5 + b*0.5)

In [41]:
def boolean_indexing(arr, minimum):
    '''Return an array of only the elements of "arr" that are greater than
    or equal to "minimum".

    FOR FULL POINTS DON'T USE LOOPS OR LIST COMPREHENSIONS.

    Parameters
    ----------
    arr: NumPy array  
    minimum: int

    Returns
    -------
    NumPy array
        Of elements of arr that are >= minimum

    >>>boolean_indexing(np.array([[3, 4, 5], [6, 7, 8]]), 7)
    array([7, 8])
    '''
    return arr[arr >= minimum]

In [42]:
boolean_indexing(np.array([[3, 4, 5], [6, 7, 8]]) , 7)

array([7, 8])

In [65]:
def size_of_multiply(A, B):
    '''If matrices A (dimensions m x n) and B (dimensions p x q) can be
    multiplied (AB), returns the shape of the result of multiplying them.
    Function DOES NOT perform the multiplication. If A and B cannot be
    multiplied, returns None. (Use the shape function.)

    DO NOT PERFORM ANY MATRIX MULTIPLICATION IN YOUR FUNCTION.

    Parameters
    ----------
    A, B: NumPy array, NumPy array

    Returns
    -------
    (int, int) or None  
    '''
    m, n = A.shape 
    p, q = B.shape 
    return (m, q) if n == p else None

In [66]:
A = np.array([[3, 4, 5], [6, 7, 8]])
B = np.zeros(shape=(3,4))
size_of_multiply(A, A)

In [67]:
def data_frame_work(df, colA, colB, colC):
    '''
    Insert a column (colC) into the dataframe that is the sum of
    colA and colB. Assume that df contains columns colA and colB and
    that these are numeric.

    Parameters
    ----------
    df: Pandas DataFrame
    colA, colB, colC: str, str, str
    '''
    df[colC] = df.colA + df.colB
    return df

In [68]:
np.mean([1,1,0,1,0])

0.6

In [71]:
def factorial(n):
    prod = 1 
    for i in range(2,n+1):
        prod *= i
    return prod

def combinations(n, k):
    return factorial(n)/(factorial(n-k) * factorial(k))

In [72]:
combinations(5,3)/2**5

0.3125

In [73]:
X = np.array([[2,4], [1,3]])
y = np.array([[1],[3]])
np.dot(X,y)

array([[14],
       [10]])

# Assessment 1 Practice

In [78]:
def max_lists(list1, list2):
    '''Compares the elements of list1, and list2 (assumed to be the same
    length),and returns the maximum value between the two, for each element.

    FOR FULL POINTS DON'T USE IMPORTS.

    Parameters
    ----------
    list1, list2: list, list
        (Of the same length)

    Returns
    -------
    list
    '''
    return [max(list1[i],list2[i]) for i in range(len(list1))]
    

In [80]:
list1 = [1,2,3,5]
list2 = [5,4,2,1]

for a,b in zip(list1,list2):
    print(a,b)


1 5
2 4
3 2
5 1


In [84]:
def invert_dictionary(d):
    '''
    Given a dictionary d, return a new dictionary with d's values
    as keys and the value for a given key being
    the set of d's keys which shared the same value.

    Parameters
    ----------
    d: dict

    Returns
    -------
    dict
        A dictionary of sets of input keys indexing the same input values
        indexed by the input values.


    >>>invert_dictionary({'a': 2, 'b': 4, 'c': 2})
    {2: {'a', 'c'}, 4: {'b'}}
    '''
    inverted_d = dict()
    for k, v in d.items():
        if v not in inverted_d:
            inverted_d[v] = set()
        inverted_d[v].add(k)
    return inverted_d

invert_dictionary({'a': 2, 'b': 4, 'c': 2})

{2: {'a', 'c'}, 4: {'b'}}

In [165]:
def matrix_multiplication(A, B):
    '''Return the matrix which is the product of matrix A and matrix B
    where A and B will be (a) integer valued (b) square matrices
    (c) of size n-by-n (d) encoded as lists of lists,  e.g.
    A = [[2, 3, 4], [6, 4, 2], [-1, 2, 0]] corresponds to the matrix
    | 2  3  4 |
    | 6  4  2 |
    |-1  2  0 |

    YOU MAY NOT USE NUMPY. Write your solution in straight python.

    Parameters
    ----------
    a, b: list of lists of integers, list of lists integers
        All inner/outer lists are of length n, so as to construct square
        matrices.

    Returns
    -------
    list of lists of integers
        The product of a matrix multiplication operation.
    
    [[sum(a*b for a,b in zip(A_row,B_col)) for B_col in zip(*B)] for A_row in A]
        
    '''
    mat_mul = []
    for a_row in A:
        temp = []
        mat_mul.append(temp)
        for b_col in zip(*B):
            temp.append(sum([a*b for a,b in zip(a_row,b_col)]))


    return mat_mul

In [166]:
A = [[1,3,8], [2,4,1],[2,4,1]] 
B = [[1,5,8], [9,6,2],[9,6,2]] 

mat_mul = []
for a_row in A:
    temp = []
    mat_mul.append(temp)
    for b_col in zip(*B):
        temp.append(sum([a*b for a,b in zip(a_row,b_col)]))

mat_mul

[[100, 71, 30], [47, 40, 26], [47, 40, 26]]

In [167]:
matrix_multiplication(A, B)

[[100, 71, 30], [47, 40, 26], [47, 40, 26]]

In [168]:
a_row = [1, 3,6]
b_col = (1,9,1)

sum_ = sum([a*b for a,b in zip(a_row,b_col)])
# for a,b in zip(a_row,b_col):
#     sum_ += a*b

sum_

34

In [169]:
D = [[2, 3, 4], [6, 4, 2], [-1, 2, 0]]
matrix_multiplication(D, D)

[[18, 26, 14], [34, 38, 32], [10, 5, 0]]

In [182]:
def reverse_index(arr, finRow, finCol):
    '''
    Reverse the row order of "arr" (i.e. so the top row is on the bottom)
    and return the sub-matrix from coordinate [0, 0] up to
    (but not including) [finRow, finCol].

    Hint: this can use two steps of slicing, which can be combined into
    a one-liner.

    FOR FULL POINTS DON'T USE LOOPS OR LIST COMPREHENSIONS.

    Parameters
    ----------
    arr: NumPy array
    finRow, finCol: int, int


    Returns
    -------
    NumPy array    
      Of an "upside down" subset of arr

    >>>arr = np.array([[ -4,  -3,  11],
                       [ 14,   2, -11],
                       [-17,  10,   3]])
    >>>reverse_index(arr, 2, 2)
    array([[-17, 10],
           [ 14,  2]])
    '''
    return arr[::-1][:finRow,:finCol]

In [183]:
arr = np.array([[ -4,  -3,  11],
                       [ 14,   2, -11],
                       [-17,  10,   3]])
arr[::-1][:2,:2]
reverse_index(arr, 2, 2)

array([[-17,  10],
       [ 14,   2]])

In [187]:
def array_work(rows, cols, scalar, matrixA):
    '''
    Create matrix of size (rows, cols) with elements initialized to the
    scalar value. Right multiply that matrix with the passed matrixA
    (i.e. AB, not BA).  Return the result of the multiplication.  You
    needn't check for matrix compatibility, but you can accomplish this in
    a single line.

    Parameters
    ----------
    rows, cols: int, int
        Size of matrix to be created
    scalar: int
        Value of each element of new matrix
    matrixA:

    Returns
    -------
    NumPy array
        Result of matrix product of row-by-col matrix of "scalar"'s times
        matrixA.

    E.g., array_work(2, 3, 5, [[3, 4], [5, 6], [7, 8]])
           [[3, 4],      [[5, 5, 5],
            [5, 6],   *   [5, 5, 5]]
            [7, 8]]
    '''
    matrixB = np.full(shape=(rows,cols), fill_value=scalar)
    return np.dot(matrixA, matrixB)

In [186]:
np.full(shape=(1,2),fill_value=9)

array([[9, 9]])

In [188]:
array_work(2, 3, 5, [[3, 4], [5, 6], [7, 8]])

array([[35, 35, 35],
       [55, 55, 55],
       [75, 75, 75]])

In [189]:
!head -5 /Users/mekdiyilma/Downloads/rent.csv

Neighborhood,City,State,med_2011,med_2014
Northeast Dallas,Dallas,TX,825.0,985.0
Paradise,Las Vegas,NV,900.0,1100.0
Maryvale,Phoenix,AZ,795.0,850.0
Upper West Side,New York,NY,2795.0,3300.0


In [192]:
rent_df = pd.read_csv('/Users/mekdiyilma/Downloads/rent.csv')
rent_df.head()

Neighborhood         City State  med_2011  med_2014
0   Northeast Dallas       Dallas    TX     825.0     985.0
1           Paradise    Las Vegas    NV     900.0    1100.0
2           Maryvale      Phoenix    AZ     795.0     850.0
3    Upper West Side     New York    NY    2795.0    3300.0
4  South Los Angeles  Los Angeles    CA    1150.0    1400.0

In [194]:
def pandas_add_increase_column(df):
    '''Adds a column to the DataFrame called 'Increase' which contains the
    amount that the median rent increased by from 2011 to 2014.

    Parameters
    ----------
    df: Pandas DataFrame

    Returns
    -------
    None
    '''
    df['Increase'] = df.med_2014 - df.med_2011
    return df.head()
    

In [195]:
pandas_add_increase_column(rent_df)

Neighborhood         City State  med_2011  med_2014  Increase
0   Northeast Dallas       Dallas    TX     825.0     985.0     160.0
1           Paradise    Las Vegas    NV     900.0    1100.0     200.0
2           Maryvale      Phoenix    AZ     795.0     850.0      55.0
3    Upper West Side     New York    NY    2795.0    3300.0     505.0
4  South Los Angeles  Los Angeles    CA    1150.0    1400.0     250.0

In [207]:
def pandas_max_rent(df):
    '''Returns a new pandas DataFrame that contains every city and the highest
    median rent from that city for 2011 and 2014.

    Note that city names are not unique so the state is tracked as well.
    For example, Portland, ME and Portland, OR are recognized as different.

    Parameters
    ----------
    df: Pandas DataFrame

    Returns
    -------
    Pandas DataFrame:
        Containing the columns: City, State, med_2011, med_2014
    '''
    return df.groupby(['City','State']).max()[['med_2011','med_2014']].head()

In [209]:
rent_df.groupby(['City','State']).aggregate(max)[['med_2011','med_2014']]

med_2011  med_2014
City              State                    
Akron             OH        690.0     725.0
Albany            NY          NaN     952.0
Albuquerque       NM       1099.0    1150.0
Alexandria        VA       2155.0    2250.0
Amherst           MA          NaN       NaN
...                           ...       ...
Westhampton Beach NY      65000.0   53900.0
Weymouth          MA       1124.0    1415.0
Wichita           KS        550.0     925.0
Wynnewood         PA          NaN       NaN
Youngstown        OH          NaN     500.0

[177 rows x 2 columns]

In [342]:
rent_df.groupby(['City','State']).aggregate(max)

Neighborhood  med_2011  med_2014  Increase
City              State                                                 
Akron             OH            West Akron     690.0     725.0      20.0
Albany            NY             West Hill       NaN     952.0       NaN
Albuquerque       NM          Westgate Hts    1099.0    1150.0     305.0
Alexandria        VA            Taylor Run    2155.0    2250.0     805.0
Amherst           MA         South Amherst       NaN       NaN       NaN
...                                    ...       ...       ...       ...
Westhampton Beach NY     Westhampton Dunes   65000.0   53900.0  -11100.0
Weymouth          MA        South Weymouth    1124.0    1415.0     291.0
Wichita           KS             Sunnyside     550.0     925.0     375.0
Wynnewood         PA            Penn Wynne       NaN       NaN       NaN
Youngstown        OH         North Heights       NaN     500.0       NaN

[177 rows x 4 columns]

In [208]:
pandas_max_rent(rent_df)

med_2011  med_2014
City        State                    
Akron       OH        690.0     725.0
Albany      NY          NaN     952.0
Albuquerque NM       1099.0    1150.0
Alexandria  VA       2155.0    2250.0
Amherst     MA          NaN       NaN

# Assessment 02 Practice

In [217]:
def roll_the_dice(n_simulations = 1000):
    '''Two unbiased, six sided, dice are thrown one time and the sum of the
    faces is observed (so if you rolled a 3 and a 1, the sum is 4). A
    simulation estimates probability that the total score is an even number
    or a number greater than 7.  This is an estimated probability, based on
    rolling the two dice n_simulations times.

    FOR FULL POINTS, THE FUNCTION MUST PERFORM A SIMULATION.

    Parameters
    ----------
    n_simulations: float
        Number of rolls of the dice

    Returns
    -------
    float
    '''
    sample_space = [i+j for j in range(1,6+1) for i in range(1,6+1)]

    simulation_result = []
    for _ in range(10):
        roll_sum = np.random.choice(sample_space)
        if roll_sum % 2 == 0 or roll_sum > 7:
            simulation_result.append(1)
        else:
            simulation_result.append(0)
    
    return sum(simulation_result)/len(simulation_result)


In [219]:
roll_the_dice()

0.7

In [240]:
def only_positive(arr):
    '''Return a numpy array containing only the rows from arr where all
    the values in that row are positive.

    FOR FULL POINTS USE NUMPY METHODS AND NO LOOPS OR LIST COMPREHENSIONS.

    Parameters
    ----------
    arr: Numpy Array (2-dimensional)

    Returns
    -------
    NumPy Array (2-dimensional)

    Example
    =======
    arr = np.array([
        [1, -1, 2],
        [3, 4, 2],
        [-8, 4, -4]
        ])
    
    only_positive(arr) returns:
    np.array([[3, 4, 2]])
    '''
    return arr[(arr>0).all(axis=1)]

In [239]:
arr = np.array([
        [1, -1, 2],
        [3, 4, 2],
        [-8, 4, -4]
        ])
arr[(arr>0).all(axis=1)]

array([[3, 4, 2]])

In [244]:
arr[np.all(arr>0, axis=1)]

array([[3, 4, 2]])

In [246]:
universities_df = pd.read_csv('/Users/mekdiyilma/Downloads/universities.csv')
universities_df.head()

name  \
0  A T Still University of Health Sciences   
1             Abilene Christian University   
2     Abraham Baldwin Agricultural College   
3                          Academy College   
4     Academy for Five Element Acupuncture   

                                             address                 Website  \
0        800 W Jefferson, Kirksville, Missouri 63501            WWW.ATSU.EDU   
1            1600 Campus Court, Abilene, Texas 79699             www.acu.edu   
2         2802 Moore Hwy, Tifton, Georgia 31793-2601            www.abac.edu   
3  1101 E. 78th Street, Suite 100, Minneapolis, M...  www.academycollege.edu   
4         305 SE 2nd Ave, Gainesville, Florida 32601   www.acupuncturist.edu   

                                                Type    Size  
0                     4-year, Private not-for-profit  3480.0  
1                     4-year, Private not-for-profit  4669.0  
2              4-year, primarily associate's, Public  3600.0  
3  4-year, primarily associate's, Private for-profit   165.0  
4                     4-year, Private not-for-profit    51.0

In [252]:
def pandas_query(df):
    '''Returns a DataFrame containing the average size of each university
    type ordered by average size in ascending order.

    Function assumes the input DataFrame contains these columns:
        name, address, Website, Type, Size

    Parameters
    ----------
    df: Pandas DataFrame

    Returns
    -------
    Pandas DataFrame
    '''
    return df.groupby('Type').mean().sort_values(by='Size',ascending=True)

In [251]:
universities_df.groupby('Type').mean().sort_values(by='Size',ascending=True)

Size
Type                                                            
4-year, primarily associate's, Private for-profit     934.380597
4-year, primarily associate's, Private not-for-...   1129.413793
4-year, Private not-for-profit                       2399.885696
4-year, Private for-profit                           3504.501859
4-year, primarily associate's, Public                6889.366197
4-year, Public                                      11478.913765

In [271]:
universities_df.loc[[1,4,5]]

name  \
1          Abilene Christian University   
4  Academy for Five Element Acupuncture   
5             Academy of Art University   

                                             address                Website  \
1            1600 Campus Court, Abilene, Texas 79699            www.acu.edu   
4         305 SE 2nd Ave, Gainesville, Florida 32601  www.acupuncturist.edu   
5  79 New Montgomery, San Francisco, California 9...     www.academyart.edu   

                             Type     Size  
1  4-year, Private not-for-profit   4669.0  
4  4-year, Private not-for-profit     51.0  
5      4-year, Private for-profit  13181.0

In [275]:
def return_loans_by_id(df):
    '''
    Takes a df and returns a df with only the requested loans.
    
    The dataframe’s index has been set to be the loan IDs (a string). 
    Your coworker asks you to retrieve all data for loans with the IDs '7484', '4423', and '9910'.

    Write the code to extract these loans by their ID in a function called return_loans_by_id.

    Parameters
    ==========
    df: Pandas DataFrame

    Returns
    =======
    Pandas DataFrame
    '''
    df.loc[['7484', '4423', '9910'],:]

In [274]:
def return_loans(df):
    '''
    Takes a df and returns a df with only the requested loans. Another coworker tells you he has a 
    great memory and thinks that these loans are stored at the 0th, 1st, and 4th indices of the dataframe. 
    Use the correct pandas method to retrieve the requested rows from the dataframe.

    Parameters
    ==========
    df: Pandas DataFrame

    Returns
    =======
    Pandas DataFrame
    '''
    df.iloc[[0,1,4],:]

In [277]:
1 - stats.binom(n=10,p=0.6).cdf(7)

0.16728975359999998

In [278]:
0.1/(0.1+0.15)

0.4

In [281]:
stats.uniform(0, 4).cdf(2) - stats.uniform(0, 4).cdf(1) +\
stats.uniform(0, 4).cdf(4) - stats.uniform(0, 4).cdf(3.5)

0.375

# Assessment Review 3

In [283]:
(0.25*0.4)/((0.25*0.4)+(0.003*0.6))

0.9823182711198428

In [285]:
sample_ages = [32, 34, 29, 29, 22, 39, 38, 37, 38, 36, 30, 26, 22, 22]
np.mean(sample_ages)

31.0

Ho: $\mu$ = 30

Ha: $\mu$ > 30

$\alpha$ = 0.05 

In [286]:
mu = 30
x_bar = np.mean(sample_ages)
se = np.sqrt(np.var(sample_ages)/len(sample_ages))
z = (x_bar - mu)/se
z

0.6199304198780666

In [291]:
1 - stats.norm(mu,se).cdf(x_bar)

0.26765179862315036

In [292]:
1 - stats.norm().cdf(z)

0.26765179862315036

Fail to reject Null

In [295]:
stats.ttest_1samp(sample_ages, 30)

Ttest_1sampResult(statistic=0.5973799001456603, pvalue=0.5605155888171379)

In [296]:
sample_space = [3, 4, 5, 7, 8, 10, 12, 13, 14, 15, 16, 18, 19, 21, 22, 23, 24, 25, 26, 31, 42, 60, 69, 86, 108, 256]

In [306]:
mean = np.mean(sample_space)
var = np.var(sample_space)
se = np.sqrt(var/len(sample_space))

alpha = stats.norm(0,se).ppf(0.5-(.95/2))
mean + alpha, mean - alpha

(16.49937235251466, 55.577550724408425)

In [320]:
mean = np.mean(sample_space)
std = np.std(sample_space)
se = std/np.sqrt(len(sample_space))

low, high = stats.norm(mean,se).ppf([0.025,0.975])
low, high

(16.49937235251465, 55.577550724408425)

In [321]:
bootstrap_sample_means = [np.mean(np.random.choice(sample_space, len(sample_space),True)) for _ in range(1000)]
np.percentile(bootstrap_sample_means, [2.5,97.5])

array([19.72788462, 57.96923077])

In [322]:
nums = [3, 4, 5, 7, 8, 10, 12, 13, 14, 15, 16, 18, 19, 21, 22, 23, 24, 25, 26, 31, 42, 60, 69, 86, 108, 256]

mean = np.mean(nums)

sigma = np.std(nums)

stand_error = sigma/np.sqrt(len(nums))

dist = stats.norm(mean, stand_error)

low = dist.ppf(0.025) #or take 2 standard errros below the mean

high = dist.ppf(0.975) #or take 2 standard errros above the mean

low, high

(16.49937235251465, 55.577550724408425)

In [323]:
means = [np.mean(np.random.choice(nums, size = len(nums))) for _ in range(1000)]

low = np.percentile(means, 2.25)

high = np.percentile(means, 97.5)

low, high

(19.324326923076924, 58.056730769230754)

## Assessment 2 Review

In [325]:
lmbda = 4
k = 5
1 - stats.poisson(mu=lmbda).cdf(k-1)

0.3711630648201266

# Extra

In [326]:
universities_df.head(5)

name  \
0  A T Still University of Health Sciences   
1             Abilene Christian University   
2     Abraham Baldwin Agricultural College   
3                          Academy College   
4     Academy for Five Element Acupuncture   

                                             address                 Website  \
0        800 W Jefferson, Kirksville, Missouri 63501            WWW.ATSU.EDU   
1            1600 Campus Court, Abilene, Texas 79699             www.acu.edu   
2         2802 Moore Hwy, Tifton, Georgia 31793-2601            www.abac.edu   
3  1101 E. 78th Street, Suite 100, Minneapolis, M...  www.academycollege.edu   
4         305 SE 2nd Ave, Gainesville, Florida 32601   www.acupuncturist.edu   

                                                Type    Size  
0                     4-year, Private not-for-profit  3480.0  
1                     4-year, Private not-for-profit  4669.0  
2              4-year, primarily associate's, Public  3600.0  
3  4-year, primarily associate's, Private for-profit   165.0  
4                     4-year, Private not-for-profit    51.0

In [328]:
universities_df.head(7)[4:0]

Empty DataFrame
Columns: [name, address, Website, Type, Size]
Index: []

In [343]:
SELECT Type, avg(Size) As avg_size
FROM universities
GROUP BY Type
ORDER BY 2 ASC;

SyntaxError: invalid syntax (<ipython-input-343-a503013cc872>, line 1)

In [ ]:
SELECT State, count(*)
FROM farmersmarkets
GROUP BY State
HAVING WIC = Y
OR WICcash = Y;