cost function for the following functions:

Ordinary Least Squares: mean squared error/RMSE, r^2 or adjusted r^2, mean absolute error <br>
Linear regression (L1 regularization) Lasso: RSS + lambda (sum of beta^2)<br>
Linear regression (L2 regularization) Ridge: RSS + lambda (sum of /beta/)<br>
Linear regression using Elastic net: RSS + lambda ((1-alpha / 2) sum of beta^2 + alpha sum of beta^2)

root note  - the first node for split; arrow comes out of the node but no arrow is point to it
parent node/internal node - test a predictor value and not the final node; have arrows pointed to it and it has arrows points out of it
leaf node -  assigns classifications/the final node; arrows coming into it, but no arrows coming out of it

Process:
For each feature, calculates information gain based on gini/enthropy impurity for all possible splits 
Makes a decision based on the highest information gain,
If node has a lower score than the leaf node, no need for split consideration or otherwise (if splitting results lowers impurity), the process repeats again.


1. Calculate the Gini impurity scores.<br>
2. If the node itself has the lowest score, then there is no point in separating the patients anymore and it becomes a leaf node.<br>
3. If separating the data results in improvement then pick the separation with the lowest impurity value.<br>




For discrete features all of its possible values are evaluated, resulting in N calculated metrics for each of the variables, being N the number of possible value for each categorical value. e.g, class vs no class

For continuous features the mean of each two consecutive values (ordered from lowest to highest) of the training data are used as possible thresholds. Impurity is calculated for each of the threshold, and the one with the lowest is set as the threshold to split on eg < threshold or >= threshold

target: predict the female gold medal winner (high jump olympics)
features: jumper_height, jumper_weight, best_jump_height,  fastest_100m_time


Used decision-tree and model does well in training, but poor on test
model performs ok during CV

We have an overfit model meaning it has high variance and it is so specific.
One method to reduce variance is to use bagging e.g, Random forest 

Random Forest Randomness
1. The dataset for each tree is generated with bootstrapping method (samples generated with replacement)
2. As we create a decision tree with the bootstrap dataset, features are randomly selected from a subspace at each step of the split without replacement

Bagging has bootstrapping and aggregation component to it and therefore can handle overfitting, reducing variance, and working with independent classifiers. RF is ensemble; it combines many weaker individual trees and form a stronger model. 

Bagging - simple ensemble technique of bootstrapping the training data and building randomly selected features for trees, and then aggregating trees to form a single model.
>> reduce variance

Boosting - ensemble technique, where predictors are made independently, but sequentially. Each tree is grown using info from the prior tree.
>> reduce bias and variance

The data that each tree in the ensemble is built on.
> independently classifiers vs sequential classifiers

How the quality of a split on a given feature and its value is evaluated.
> low variance  vs low bias

The general depth of each tree.
?

The bias-variance trade-off associated with each tree in the ensemble.
> low variance  vs low bias

How the ensemble can achieve a low-bias, low-variance model.
> low variance  vs low bias

In [3]:
import numpy as np
import pandas as pd

In [6]:
def sum_to_target(nums, target):
    '''
    Given an array of integers and a target integer, return 
    indices of the two numbers in the array that sum to equal 
    the target.

    You may assume that each input would have exactly one solution,  
    and you may not use an element at the same index more than once.
    
    Return the indices in ascending order.   
    For full points your solution should have a runtime of O(N). 

    Parameters
    ----------
    nums: list
    target: int

    Returns
    -------
    list
    
    Input: nums = [3,2,4], target = 6
    Output: [1,2]
    '''
    for i, n1 in enumerate(nums):
        for j, n2 in enumerate(nums):
            if i!=j and n1+n2 == target:
                return [i,j]
    return None

sum_to_target([3,2,4], 6)               
        

[1, 2]

In [34]:
def split_node(X, y, col, split_val):
    '''Split a feature matrix X and the target array y 
    into "left" and "right" arrays determined by splitting 
    on "split_val" in col of the X matrix.
    
    The "left" matrices of X and y contain the rows corresponding 
    to values in col <= split value, while the "right" matrices 
    contain the rows where col > split value.  Return the four arrays 
    separately (see example below).

    You can assume that all columns in X are continuous values.  
    col is an integer (0 indexed) that indicates which column of X 
    to use to split the X and y arrays.

    Return empty arrays for the left or right arrays if no values 
    are returned.

    FOR FULL POINTS DON'T USE LOOPS OR LIST COMPREHENSIONS.

    Parameters
    ----------
    X: NumPy array
    y: NumPy array  
    col: int
    split_val: float

    Returns
    -------
    NumPy array, NumPy array, NumPy array, NumPy array

    >>>X = np.array([[ 5.5,  2.4,  3.7],
                     [ 5.5,  2.3,  3.8],
                     [ 6.1,  3.0,  4.9],
                     [ 5.2,  3.5,  1.5],
                     [ 5.7,  2.6,  3.5]])

    >>>y = np.array([1, 1, 2, 0, 1])

    >>>X_left, y_left, X_right, y_right = split_node(X, y, 1, 2.6)

    >>>X_left
    array([[5.5, 2.4, 3.7],
           [5.5, 2.3, 3.8],
           [5.7, 2.6, 3.5]])

    >>>y_left
    array([1, 1, 1])
    '''
    mask = X[:,col] <= split_val
    X_left, y_left, X_right, y_right = X[mask], y[mask], X[~mask], y[~mask]
    return X_left, y_left, X_right, y_right
    

In [35]:
X = np.array([[ 5.5,  2.4,  3.7],
                     [ 5.5,  2.3,  3.8],
                     [ 6.1,  3.0,  4.9],
                     [ 5.2,  3.5,  1.5],
                     [ 5.7,  2.6,  3.5]])
mask = X[:,1] <= 2.6
y = np.array([1, 1, 2, 0, 1])
X[~idx]
y[~idx]

array([2, 0])

In [36]:
idx

array([ True,  True, False, False,  True])

In [37]:
split_node(X, y, 1, 2.6)

(array([[5.5, 2.4, 3.7],
        [5.5, 2.3, 3.8],
        [5.7, 2.6, 3.5]]),
 array([1, 1, 1]),
 array([[6.1, 3. , 4.9],
        [5.2, 3.5, 1.5]]),
 array([2, 0]))

In [38]:
def calculate_entropy(arr):
    '''Return the Shannon entropy of a NumPy array containing only
    two classes (integers 0 and 1).

    You can assume that the array will always contain one or more values.
    Do not assume that all classes are present in arr
    
    FOR FULL POINTS DO NOT USE AN IMPORTED ENTROPY FUNCTION

    Parameters
    ----------
    arr: NumPy array
        Elements of of arr are binary (0 or 1)

    Returns
    -------
    float
    '''
    pass

In [39]:
arr = [0,1,2,0,0,2]

for i in arr:
    

In [40]:
def estimate_shannon_entropy(dna_sequence):
    m = len(dna_sequence)
    bases = collections.Counter([tmp_base for tmp_base in dna_sequence])

    shannon_entropy_value = 0
    for base in bases:
        # number of residues
        n_i = bases[base]
        # n_i (# residues type i) / M (# residues in column)
        p_i = n_i / float(m)
        entropy_i = p_i * (math.log(p_i, 2))
        shannon_entropy_value += entropy_i

    return shannon_entropy_value * -1

In [52]:
import collections
import math
def estimate_shannon_entropy(arr):
    m = len(arr)
    count_d = collections.Counter(arr)

    shannon_entropy_value = 0
    
    for k, v in count_d.items():
        p_i = v / float(m)
        entropy_i = p_i * (math.log(p_i, 2))
        shannon_entropy_value += entropy_i

    return shannon_entropy_value * -1

estimate_shannon_entropy(arr)

0 3
1 1
2 2


1.4591479170272446

In [44]:
collections.Counter(arr)

Counter({0: 3, 1: 1, 2: 2})

In [53]:
def make_series(start, length, index):
    '''Create a pandas Series of length "length" with index "index"
    and with elements that are sequential integers starting from "start".
    You may assume the length of index will be "length".

    Parameters
    ----------
    start, length: int, int
    index: list
        Index of length "length"

    Returns
    -------
    Pandas Series

    >>>print(make_series(5, 3, ['a', 'b', 'c']))
    a    5
    b    6
    c    7
    dtype: int64
    '''
    return pd.Series(np.arange(start,start+length), index=index)

In [59]:
pd.Series(np.arange(5,5+3), index=['a', 'b', 'c'])

a    5
b    6
c    7
dtype: int64

In [63]:
nums = [2,3,4]
target = 6
for i, n1 in enumerate(nums):
#         for j, n2 in enumerate(nums):
#             if i!=j and n1+n2 == target:
#                 return [i,j]
    print(i, n1)

0 2
1 3
2 4


```SELECT Neighborhood
FROM rent
WHERE City = 'San Francisco'
AND State = 'CA'
AND med_2014 IS NOT NULL
AND med_2011 IS NOT NULL
ORDER BY (med_2014 - med_2011)/med_2011 * 100.0 DESC
LIMIT 5;```

SELECT r.Neighborhood, r.med_2014, b.med_2014
FROM rent AS r
JOIN buy AS b
ON r.City = b.City
WHERE r.City = 'San Francisco'

In [67]:
Parent_Node = np.array([6, 5, 8, 8, 5, 4, 2, 4, 4])
Left_Child_Node = np.array([6, 5, 8, 8])
Right_Child_Node = np.array([5, 4, 2, 4, 4])

In [71]:
sum((Parent_Node - np.mean(Parent_Node))**2)

30.888888888888882

In [72]:
sum((Left_Child_Node - np.mean(Left_Child_Node))**2)

6.75

In [73]:
sum((Right_Child_Node - np.mean(Right_Child_Node))**2)

4.8

In [75]:
test_Node = np.array([156,167,160,170,172])
sum((test_Node - np.mean(test_Node))**2)

184.0